spring:
  application:
    name: kaola-share

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3307/kaola
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-wyl-ai
    region: cn-beijing